// this file is automatically generated by git.version.ts script
export const versions = {version: '0.0.0', revision: '49c5e9fbb4312c9437fdef2a582d54d78c35aad3', branch: '49c5e9fbb4312c9437fdef2a582d54d78c35aad3'};
