// this file is automatically generated by git.version.ts script
export const versions = {version: '0.0.0', revision: '3406f2ea5bb91b55124dbf96d591f028adfdc3ce', branch: '3406f2ea5bb91b55124dbf96d591f028adfdc3ce'};
