# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  #  build and test jobs go here
  deploy-job:
    docker:
      - image: circleci/node:7.10
    working_directory:  ~/angular-circleCI
    steps:
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync ./dist s3://rollbar-example --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}*/
        
      # run tests!
      #- run: npm test

 
      


